apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports}}
    - port: {{ .port }}
      targetPort: {{ .targetPort}}
      protocol: {{ .protocol}}
      name: {{ .name }}
      {{- end}}
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
